apiVersion: apps/v1
kind: Deployment
metadata:
  name: buksfrontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buksfrontend
  template:
    metadata:
      labels:
        app: buksfrontend
    spec:
      containers:
      - name: buksfrontend
        image: japhetism/buksfrontend
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80



---


apiVersion: v1
kind: Service
metadata:
  name: buksfrontend
spec:
  type: NodePort
  selector:
    app: buksfrontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000

