apiVersion: apps/v1
kind: Deployment
metadata:
  name: buksbackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buksbackend
  template:
    metadata:
      labels:
        app: buksbackend
    spec:
      containers:
      - name: buksbackend
        image: japhetism/buksbackend
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000



---


apiVersion: v1
kind: Service
metadata:
  name: buksbackend
spec:
  type: NodePort
  selector:
    app: buksbackend
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    nodePort: 32767

