apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaprojectfrontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scaprojectfrontend
  template:
    metadata:
      labels:
        app: scaprojectfrontend
    spec:
      containers:
      - name: myapp
        image: japhetism/scaprojectfrontend
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80



---


apiVersion: v1
kind: Service
metadata:
  name: scaprojectfrontend
spec:
  type: NodePort
  selector:
    app: scaprojectfrontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000

